### ISSUE TITLE
Criação do Diagrama BPMN

### ISSUE THREAD

**Issue by Peedrooo** [UnBArqDsw2023-2/2023.2_G5_ProjetoAmericanas#1]
### Summary

Criação do Diagrama BPMN que descreve a abordagem que usaremos no projeto. A abordagem utilizada será o SCRUM com KANBAN. E deve ser definido no diagrama o fluxo das atividades e de organização da metodologia e da organização da equipe

### Motivation

Organizar o projeto e definir a metodologia de desenvolvimento.

### Additional Context

[Link de inspiração](https://translate-me.github.io/docs/metodologia/#34-elementos-rup)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Peedrooo** [comment]
Galera, achei uma pagina do semestre anterior que se assemelha muito com a nossa, se liguem: https://unbarqdsw2023-1.github.io/2023.1_G1_ProjetoMercadoLivre/#/Base/1.2.ProcessosMetodologiasAbordagens

@PabloChristianno 
@leomichalski 

Seguindo esse modelo aí deve dar muito bom

**Comment by leomichalski** [comment]
Mais algumas referências:
* Sobre XP: https://www.slideshare.net/hotpop/introduo-programao-extrema-extreme-programming-xp
* Projeto antigo: https://translate-me.github.io/docs/metodologia/
* Métodos ágeis: https://www.elirodrigues.com/wp-content/uploads/2013/10/PMI-ACP1.png
