### ISSUE TITLE
Criação do Rich Picture de fluxo de avaliação de produtos

### ISSUE THREAD

**Issue by Peedrooo** [UnBArqDsw2023-2/2023.2_G5_ProjetoAmericanas#3]
### Summary

Realizar o rich picture do fluxo de avaliação de produtos compreendido no sistema da Americanas.

### Motivation

.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fellipepcs** [comment]
- [ ] Fellipe
- [ ]  Carlos 
- [ ]  José

**Comment by Peedrooo** [comment]
@CDGodoy precisamos que tu suba tua versão de rich picture
