### ISSUE TITLE
Diagrama de Componentes

### ISSUE THREAD

**Issue by Peedrooo** [UnBArqDsw2023-2/2023.2_G5_ProjetoAmericanas#79]
### Summary

![image](https://github.com/UnBArqDsw2023-2/2023.2_G5_ProjetoAmericanas/assets/69866365/eca08f41-2f79-4617-98f8-4717e46c84b2)

### Motivation

Correção dos artefatos

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by leomichalski** [comment]
@Peedrooo não vai ser feito o diagrama de componentes, somente o de implantação
