### ISSUE TITLE
Diagrama de Implantação

### ISSUE THREAD

**Issue by Peedrooo** [UnBArqDsw2023-2/2023.2_G5_ProjetoAmericanas#81]
### Summary

Criação do diagrama de implantação

### Motivation

Correção dos artefatos

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by leomichalski** [comment]
Em andamento: 

https://github.com/UnBArqDsw2023-2/2023.2_G5_ProjetoAmericanas/blob/diagrama-de-componentes/docs/img/diagrama_de_implantacao.png
