### ISSUE TITLE
Criar Modelo de implantação

### ISSUE THREAD

**Issue by Peedrooo** [UnBArqDsw2023-2/2023.2_G5_ProjetoAmericanas#89]
### Summary

Estudar e criar Modelo de implantação

### Motivation

Criar Modelo de implantação

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by leomichalski** [comment]
Em andamento: 

https://github.com/UnBArqDsw2023-2/2023.2_G5_ProjetoAmericanas/blob/diagrama-de-componentes/docs/img/diagrama_de_implantacao.png

[](https://github.com/UnBArqDsw2023-2/2023.2_G5_ProjetoAmericanas/blob/diagrama-de-componentes/docs/img/diagrama_de_implantacao.png)
